In [1]:
import numpy as np 
a = np.random.randint(1,100,20)
print(a)

[98 24  5 95 24 23  6 59 15 21  5 71 56 39 68 83 89 41  4 60]


In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[ 3 73 45 48]
 [91 60 37 97]
 [17 65 90 59]
 [94 13 18 18]
 [ 9 96 75 63]
 [45 82 24 28]]


In [ ]:
# np.sort()

np.sort(a)

array([ 4,  5,  5,  6, 15, 21, 23, 24, 24, 39, 41, 56, 59, 60, 68, 71, 83,
       89, 95, 98])

In [ ]:
#descending order

np.sort(a)[::-1]

array([98, 95, 89, 83, 71, 68, 60, 59, 56, 41, 39, 24, 24, 23, 21, 15,  6,
        5,  5,  4])

In [12]:
np.sort(b) # row waise sorted (default)

array([[ 3, 45, 48, 73],
       [37, 60, 91, 97],
       [17, 59, 65, 90],
       [13, 18, 18, 94],
       [ 9, 63, 75, 96],
       [24, 28, 45, 82]])

In [ ]:
np.sort(b,axis = 0) #column wise sorting 

array([[ 3, 13, 18, 18],
       [ 9, 60, 24, 28],
       [17, 65, 37, 48],
       [45, 73, 45, 59],
       [91, 82, 75, 63],
       [94, 96, 90, 97]])

In [13]:
# np.append()

np.append(a,150)

array([ 98,  24,   5,  95,  24,  23,   6,  59,  15,  21,   5,  71,  56,
        39,  68,  83,  89,  41,   4,  60, 150])

In [15]:
# now  in 2d to add one more column let say (1,1,1,1)
np.append(b,np.ones((b.shape[0],1)),axis = 1 )


array([[ 3., 73., 45., 48.,  1.],
       [91., 60., 37., 97.,  1.],
       [17., 65., 90., 59.,  1.],
       [94., 13., 18., 18.,  1.],
       [ 9., 96., 75., 63.,  1.],
       [45., 82., 24., 28.,  1.]])

In [ ]:
# np.concatenate()

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 0)  # concatenate along raw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis = 1) # concatenate along column


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [21]:
# np.unique 
e = np.array([1,1,1,2,3,3,4,5,5,6,7])
f = np.array([[7,7,2,7,5,2],[2,1,9,8,8,7]])
print(e)
print(f)


[1 1 1 2 3 3 4 5 5 6 7]
[[7 7 2 7 5 2]
 [2 1 9 8 8 7]]


In [32]:
np.unique(e)


array([1, 2, 3, 4, 5, 6, 7])

In [33]:
np.unique(f)

array([1, 2, 5, 7, 8, 9])

In [ ]:
# np.expand_dims
