In [5]:
import numpy as np 
a = np.random.randint(1,100,20)
print(a)

[42 26 12 20 60 22 78 17  6 96 78 50 80 94 12 83 20 51 30 57]


In [6]:
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[20 91 35 95]
 [41 51 59 83]
 [ 9 54 75 36]
 [29 58 27 73]
 [57 22 13 59]
 [68 57 93 23]]


In [ ]:
# np.sort()

np.sort(a)

array([ 4,  5,  5,  6, 15, 21, 23, 24, 24, 39, 41, 56, 59, 60, 68, 71, 83,
       89, 95, 98])

In [ ]:
#descending order

np.sort(a)[::-1]

array([98, 95, 89, 83, 71, 68, 60, 59, 56, 41, 39, 24, 24, 23, 21, 15,  6,
        5,  5,  4])

In [12]:
np.sort(b) # row waise sorted (default)

array([[ 3, 45, 48, 73],
       [37, 60, 91, 97],
       [17, 59, 65, 90],
       [13, 18, 18, 94],
       [ 9, 63, 75, 96],
       [24, 28, 45, 82]])

In [ ]:
np.sort(b,axis = 0) #column wise sorting 

array([[ 3, 13, 18, 18],
       [ 9, 60, 24, 28],
       [17, 65, 37, 48],
       [45, 73, 45, 59],
       [91, 82, 75, 63],
       [94, 96, 90, 97]])

In [13]:
# np.append()

np.append(a,150)

array([ 98,  24,   5,  95,  24,  23,   6,  59,  15,  21,   5,  71,  56,
        39,  68,  83,  89,  41,   4,  60, 150])

In [15]:
# now  in 2d to add one more column let say (1,1,1,1)
np.append(b,np.ones((b.shape[0],1)),axis = 1 )


array([[ 3., 73., 45., 48.,  1.],
       [91., 60., 37., 97.,  1.],
       [17., 65., 90., 59.,  1.],
       [94., 13., 18., 18.,  1.],
       [ 9., 96., 75., 63.,  1.],
       [45., 82., 24., 28.,  1.]])

In [ ]:
# np.concatenate()

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis = 0)  # concatenate along raw

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis = 1) # concatenate along column


array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [21]:
# np.unique 
e = np.array([1,1,1,2,3,3,4,5,5,6,7])
f = np.array([[7,7,2,7,5,2],[2,1,9,8,8,7]])
print(e)
print(f)


[1 1 1 2 3 3 4 5 5 6 7]
[[7 7 2 7 5 2]
 [2 1 9 8 8 7]]


In [32]:
np.unique(e)


array([1, 2, 3, 4, 5, 6, 7])

In [33]:
np.unique(f)

array([1, 2, 5, 7, 8, 9])

In [6]:
# np.expand_dims
import numpy as np 
a = np.random.randint(1,100,20)
print(a)
np.shape(a)

[55 50 92 24 38 22 76 61 98 69 13 20 86 42 34 15 90  5 20 55]


(20,)

In [4]:
c = np.expand_dims(a,axis = 1)
print(c)
np.shape(c)

[[94]
 [84]
 [75]
 [ 6]
 [52]
 [ 8]
 [ 1]
 [92]
 [12]
 [ 5]
 [76]
 [17]
 [26]
 [13]
 [38]
 [ 2]
 [32]
 [89]
 [81]
 [77]]


(20, 1)

In [5]:
b = np.expand_dims(a,axis = 0)
print(b)
np.shape(b)

[[94 81 70 25 85 29 30 47 45 45 85 33 62 23 38 45 45 30 43 25]]


(1, 20)

In [7]:

# np.where

a




array([42, 26, 12, 20, 60, 22, 78, 17,  6, 96, 78, 50, 80, 94, 12, 83, 20,
       51, 30, 57])

In [10]:
# to find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  6,  7,  8,  9, 12, 16, 19]),)

In [13]:
# replace all the values those values > 50 with 0 
np.where(a>50,0,a)  # np.where(condition,true , false) , i.e. if condition will full fill print true i.e. o in this case
                     # if condition is false do not replace anything 

array([ 0, 50,  0, 24, 38, 22,  0,  0,  0,  0, 13, 20,  0, 42, 34, 15,  0,
        5, 20,  0])

In [14]:
# replace even no. with zero 
np.where(a%2 == 0,0,a)

array([55,  0,  0,  0,  0,  0,  0, 61,  0, 69, 13,  0,  0,  0,  0, 15,  0,
        5,  0, 55])

In [15]:
# np.argmax
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [21]:
# to find the index of largest number
int(np.argmax(a))


8

In [22]:
# in 2D
b = np.random.randint(1,100,24).reshape(6,4)
print(b)

[[86 15 77 46]
 [44  5 30 88]
 [97 84 57 45]
 [81 16 29 34]
 [92 64 51 49]
 [94 65 51 10]]


In [ ]:
np.argmax(b,axis = 0) # for numpy axis = o , means coulun wise 

array([2, 2, 0, 1])

In [24]:
    # np.cumsum 
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [25]:
np.cumsum(a)

array([ 55, 105, 197, 221, 259, 281, 357, 418, 516, 585, 598, 618, 704,
       746, 780, 795, 885, 890, 910, 965])

In [26]:
b

array([[86, 15, 77, 46],
       [44,  5, 30, 88],
       [97, 84, 57, 45],
       [81, 16, 29, 34],
       [92, 64, 51, 49],
       [94, 65, 51, 10]])

In [28]:
np.cumsum(b,axis = 0) #column wise

array([[ 86,  15,  77,  46],
       [130,  20, 107, 134],
       [227, 104, 164, 179],
       [308, 120, 193, 213],
       [400, 184, 244, 262],
       [494, 249, 295, 272]])

In [ ]:
# np.cumprod
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [31]:
np.cumprod(a)

array([                  55,                 2750,               253000,
                    6072000,            230736000,           5076192000,
               385790592000,       23533226112000,     2306256158976000,
         159131674969344000,  2068711774601472000,  4480747344610336768,
       -2037353911411621888,  6664856089259638784,  5244178150313099264,
        4875695959858282496, -3909221381783814144, -1099362835209519104,
       -3540512630480830464,  8185990134359392256])

In [32]:
# np.percentile
a


array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [34]:
int(np.percentile(a,100)) # for 100 %ile i.e. max

98

In [ ]:
int(np.percentile(a,0)) # for 0%ile i.e. mininmum 
# similarlly we can do it for any percentile 

5

In [36]:
# np.histogram
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [37]:
np.histogram(a,bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 4, 2, 1, 3, 2, 1, 1, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [42]:
# np.corrcoef()
salary = np.array([200000,250000,300000,375000,425000,500000])
experience = np.array([0,1,2,3,4,5])

np.corrcoef(salary,experience)


array([[1.        , 0.99736495],
       [0.99736495, 1.        ]])

In [45]:
 #np.isin()  np.isin() is a powerful function used to test the presence of elements from one array within another.isinstance
items = np.array([17,27,92,98,55,81,50])   
np.isin(a,items)                     

array([ True,  True,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False,  True])

In [46]:
a[np.isin(a,items)]

array([55, 50, 92, 98, 55])

In [47]:
# numpy.flip(m, axis=None) 
#reverses the order of elements in an array along a specified axis.
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [ ]:
np.flip(a)


array([55, 20,  5, 90, 15, 34, 42, 86, 20, 13, 69, 98, 61, 76, 22, 38, 24,
       92, 50, 55])

In [49]:
b

array([[86, 15, 77, 46],
       [44,  5, 30, 88],
       [97, 84, 57, 45],
       [81, 16, 29, 34],
       [92, 64, 51, 49],
       [94, 65, 51, 10]])

In [ ]:
np.flip(b) # if axis is not defined , by default flips along both axis 


array([[10, 51, 65, 94],
       [49, 51, 64, 92],
       [34, 29, 16, 81],
       [45, 57, 84, 97],
       [88, 30,  5, 44],
       [46, 77, 15, 86]])

In [ ]:
# np.put(a, ind, v, mode='raise')
# replaces specific elements of an array with given values
a

array([55, 50, 92, 24, 38, 22, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [8]:
np.put(a,[0,5],[51,19])
a

array([51, 26, 12, 20, 60, 19, 78, 17,  6, 96, 78, 50, 80, 94, 12, 83, 20,
       51, 30, 57])

In [54]:
# np.delete(arr, obj, axis=None)
# returns a new array with sub-arrays  removed along a specified axis.
np.delete(a,[5,7,9])

array([51, 50, 92, 24, 38, 76, 98, 13, 20, 86, 42, 34, 15, 90,  5, 20, 55])

In [ ]:
# SET FUNCTIONS 

# np.union1d()
# np.intersect1d()
# np.setdiff1d
# np.setxor1d
# np.in1d

In [8]:
m = np.array([1,2,3,5,6,9])
n = np.array([3,4,5,2,6,9,11])

# np.union1d()

np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  6,  9, 11])

In [56]:
# np.intersect1d
np.intersect1d(m,n)

array([2, 3, 5, 6, 9])

In [ ]:
# np.setdiff1d()

np.setdiff1d(m,n)

array([1])

In [ ]:
# np.setxor1d(). excluding common elements
np.setxor1d(m,n)

array([ 1,  4, 11])

In [9]:
# np.in1d()

np.isin(m,1)


array([ True, False, False, False, False, False])

In [61]:
# np.clip(a, a_min, a_max, out=None, kwargs)


# np.clip() is used to limit the values in an array to a specified range. Any values in 
#  the array that are smaller than the min are set to the min, and any values that are larger than 
#  the max are set to the max.

a

array([51, 50, 92, 24, 38, 19, 76, 61, 98, 69, 13, 20, 86, 42, 34, 15, 90,
        5, 20, 55])

In [10]:
import numpy as np
np.clip(a,a_min = 33,a_max = 60)


array([51, 33, 33, 33, 60, 33, 60, 33, 33, 60, 60, 50, 60, 60, 33, 60, 33,
       51, 33, 57])