In [ ]:
#Boolean indexing

import numpy as np

#boolean indexing 
# a = np.random.randint(1,100,24).reshape(6,4)
# a

# randint for generating random number b/w specific range and specific numbers.
# as (1,100,24) 1 is initial (inclusive) and 100 is final (exclusive). and 24 is the number of element we are chossing 

                      

array([[81, 25, 55, 99],
       [20, 94, 89, 76],
       [97, 60, 50, 30],
       [45, 44, 44, 17],
       [78, 51, 56, 95],
       [90, 14, 49, 86]])

In [ ]:
# find all the numbers which are greater than 45
# a[a>45]

array([81, 55, 99, 94, 89, 76, 97, 60, 50, 78, 51, 56, 95, 90, 49, 86])

In [ ]:
#find the numbers which are greater than 45 and also even number 
# a[(a>45) & (a%2 == 0)]


array([94, 76, 60, 50, 78, 56, 90, 86])

In [ ]:
#find the numbers which are greater than 45 and also a odd number
# a[(a>45) & ~(a%2 == 0)]

array([81, 55, 99, 89, 97, 51, 95, 49])

In [22]:
#Broadcasting 
a = np.arange(12).reshape(4,3)
b = np.arange(3)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]


In [25]:
print(a.shape)
print(b.shape)
print(a)
print(b)
print(a+b)

(4, 3)
(3,)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [28]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
print(a)
print(b)
# print(a+b) will not work as by following the rule of broadcasting a = (3,4) and b will become b = (3,3).
#              and by rule error will rasie as there is dimenstional error , 
#     i.e. dimention of a = (3,4) will not be equal to b = (3,3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0 1 2]


In [ ]:
a = np.arange(4).reshape(1,4)
b = np.arange(4).reshape(4,1)
print(a)
print(b)
print(a+b) # here both a and b will become (4,4)

[[0 1 2 3]]
[[0]
 [1]
 [2]
 [3]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [ ]:
a = np.arange(4).reshape(2,2)
b = np.arange(1).reshape(1)
print(a)
print(b)
print(a+b) # sequence of b will be b= (1,1) - b=(2,1) - b= (2,2) then both a = (2,2 ) and b =(2,2)

[[0 1]
 [2 3]]
[0]
[[0 1]
 [2 3]]


In [ ]:
a = np.arange(20).reshape(5,4)
b = np.arange(20).reshape(4,5)
print(a)
print(b)
# print(a+b) will not work as there is not any one in a and b 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


ValueError: operands could not be broadcast together with shapes (5,4) (4,5) 